name: Nareta
options:
  bundleIdPrefix: com.fragde
  deploymentTarget:
    iOS: "18.0"
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: "5.0"
    MARKETING_VERSION: "0.1.0"
    CURRENT_PROJECT_VERSION: "2"
targets:
  Nareta:
    type: application
    platform: iOS
    sources:
      - path: Nareta
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: app.nareta
        DEVELOPMENT_TEAM: J9UUQMJBMJ
        INFOPLIST_KEY_ITSAppUsesNonExemptEncryption: NO
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_FILE: Config/Info.plist
        INFOPLIST_KEY_CFBundleDisplayName: NARETA
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait
        INFOPLIST_KEY_UIUserInterfaceStyle: Light
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: "1"
        CODE_SIGN_STYLE: Automatic
        ENABLE_PREVIEWS: YES
