name: Nareta
options:
  bundleIdPrefix: app.nareta
  deploymentTarget:
    iOS: "18.0"
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: "5.0"
    MARKETING_VERSION: "0.1.0"
    CURRENT_PROJECT_VERSION: "5"
    DEVELOPMENT_TEAM: J9UUQMJBMJ
    CODE_SIGN_STYLE: Automatic
targets:
  Nareta:
    type: application
    platform: iOS
    sources:
      - path: Nareta
      - path: Shared
    dependencies:
      - target: NaretaWidget
    entitlements:
      path: Config/Nareta.entitlements
      properties:
        com.apple.security.application-groups:
          - group.app.nareta
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: app.nareta
        INFOPLIST_KEY_ITSAppUsesNonExemptEncryption: NO
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_FILE: Config/Info.plist
        INFOPLIST_KEY_CFBundleDisplayName: NARETA
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait
        INFOPLIST_KEY_UIUserInterfaceStyle: Light
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: "1"
        ENABLE_PREVIEWS: YES
  NaretaWidget:
    type: app-extension
    platform: iOS
    sources:
      - path: NaretaWidget
      - path: Shared
    entitlements:
      path: Config/NaretaWidget.entitlements
      properties:
        com.apple.security.application-groups:
          - group.app.nareta
    info:
      path: Config/NaretaWidget-Info.plist
      properties:
        CFBundleDisplayName: NARETA
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: app.nareta.widget
        TARGETED_DEVICE_FAMILY: "1"
        SKIP_INSTALL: YES
